import {
  mockIp,
  mockReqId
} from '../utils/mock';

export function genCartGroupData() {
  const resp = {
    data: {
      isNotEmpty: true,
      storeGoods: [{
        storeId: '1000',
        storeName: '云Mall大连旗舰店',
        storeStatus: 1,
        totalDiscountSalePrice: '9990',
        promotionGoodsList: [{
            title: '满减满折回归',
            promotionCode: 'MERCHANT',
            promotionSubCode: 'MYJ',
            promotionId: '159174555838121985',
            tagText: ['满100元减99.9元'],
            promotionStatus: 3,
            tag: '满减',
            description: '满100元减99.9元,已减99.9元',
            doorSillRemain: null,
            isNeedAddOnShop: 0,
            goodsPromotionList: [{
                uid: '88888888205468',
                saasId: '88888888',
                storeId: '1000',
                spuId: '12',
                skuId: '135691622',
                isSelected: 1,
                thumb: 'https://bkimg.cdn.bcebos.com/pic/9e3df8dcd100baa1dea1d5124d10b912c9fc2e8d?x-bce-process=image/resize,m_lfit,w_235,h_235,limit_1/format,f_auto',
                title: '大连红灯樱桃',
                primaryImage: 'https://bkimg.cdn.bcebos.com/pic/35a85edf8db1cb139b67cc68d554564e92584bbb?x-bce-process=image/watermark,image_d2F0ZXIvYmFpa2U5Mg==,g_7,xp_5,yp_5/format,f_auto',
                quantity: 1,
                stockStatus: true,
                stockQuantity: 3,
                price: '9900',
                originPrice: '16900',
                tagPrice: null,
                titlePrefixTags: [{
                  text: '新品'
                }, {
                  text: '火爆'
                }],
                roomId: null,
                specInfo: [{
                    specTitle: '重量',
                    specValue: '5KG',
                  },
                  {
                    specTitle: '类型',
                    specValue: '小果',
                  },
                ],
                joinCartTime: '2020-06-29T07:55:40.000+0000',
                available: 1,
                putOnSale: 1,
                etitle: null,
              },
              {
                uid: '88888888205468',
                saasId: '88888888',
                storeId: '1000',
                spuId: '18',
                skuId: '135681631',
                isSelected: 1,
                thumb: 'https://bkimg.cdn.bcebos.com/pic/38dbb6fd5266d016f2f6713d9f2bd40735fa353c?x-bce-process=image/watermark,image_d2F0ZXIvYmFpa2U4MA==,g_7,xp_5,yp_5/format,f_auto',
                title: '大连明珠樱桃',
                primaryImage: 'https://bkimg.cdn.bcebos.com/pic/38dbb6fd5266d016f2f6713d9f2bd40735fa353c?x-bce-process=image/watermark,image_d2F0ZXIvYmFpa2U4MA==,g_7,xp_5,yp_5/format,f_auto',
                quantity: 1,
                stockStatus: true,
                stockQuantity: 177,
                price: '29800',
                originPrice: '40000',
                tagPrice: null,
                titlePrefixTags: null,
                roomId: null,
                specInfo: [{
                    specTitle: '重量',
                    specValue: '5kg',
                  },
                  {
                    specTitle: '类型',
                    specValue: '大果',
                  },
                ],
                joinCartTime: '2020-06-29T07:55:27.000+0000',
                available: 1,
                putOnSale: 1,
                etitle: null,
              },
              {
                uid: '88888888205468',
                saasId: '88888888',
                storeId: '1000',
                spuId: '13',
                skuId: '135698362',
                isSelected: 1,
                thumb: 'https://bkimg.cdn.bcebos.com/pic/9825bc315c6034a8fa166248c213495408237607?x-bce-process=image/watermark,image_d2F0ZXIvYmFpa2UxMTY=,g_7,xp_5,yp_5/format,f_auto',
                title: '大连湾生蚝',
                primaryImage: 'https://img.thehour.cn/2019/06/14/15604815989316676015394926880873.gif?w=859&h=784',
                quantity: 13,
                stockStatus: true,
                stockQuantity: 9,
                price: '29900',
                originPrice: '0',
                tagPrice: null,
                titlePrefixTags: [{
                  text: '火爆'
                }],
                roomId: null,
                specInfo: [{
                    specTitle: '重量',
                    specValue: '5kg',
                  },
                  {
                    specTitle: '大小',
                    specValue: '大',
                  },
                ],
                joinCartTime: '2020-06-29T07:54:43.000+0000',
                available: 1,
                putOnSale: 1,
                etitle: null,
              },
              {
                uid: '88888888205468',
                saasId: '88888888',
                storeId: '1000',
                spuId: '7',
                skuId: '135681625',
                isSelected: 1,
                thumb: 'https://bkimg.cdn.bcebos.com/pic/0824ab18972bd40735fa0b4ca0db89510fb30f24a37d?x-bce-process=image/resize,m_lfit,h_168,limit_1/format,f_auto',
                title: '大连俄八樱桃',
                primaryImage: 'https://bkimg.cdn.bcebos.com/pic/0824ab18972bd40735fa0b4ca0db89510fb30f24a37d?x-bce-process=image/resize,m_lfit,h_168,limit_1/format,f_auto',
                quantity: 1,
                stockStatus: true,
                stockQuantity: 0,
                price: '29900',
                originPrice: '29900',
                tagPrice: null,
                titlePrefixTags: null,
                roomId: null,
                specInfo: [{
                    specTitle: '重量',
                    specValue: '10kg',
                  },
                  {
                    specTitle: '类型',
                    specValue: '中果',
                  },
                ],
                joinCartTime: '2020-06-29T07:55:00.000+0000',
                available: 1,
                putOnSale: 1,
                etitle: null,
              },
            ],
            lastJoinTime: '2020-06-29T07:55:40.000+0000',
          },
          {
            title: null,
            promotionCode: 'EMPTY_PROMOTION',
            promotionSubCode: null,
            promotionId: null,
            tagText: null,
            promotionStatus: null,
            tag: null,
            description: null,
            doorSillRemain: null,
            isNeedAddOnShop: 0,
            goodsPromotionList: [{
              uid: '88888888205468',
              saasId: '88888888',
              storeId: '1000',
              spuId: '11',
              skuId: '135691629',
              isSelected: 0,
              thumb: 'https://bkimg.cdn.bcebos.com/pic/09fa513d269759eeb97ffa3eb2fb43166d22df1c?x-bce-process=image/resize,m_lfit,w_220,limit_1/format,f_auto',
              title: '大连美早樱桃',
              primaryImage: 'https://bkimg.cdn.bcebos.com/pic/09fa513d269759eeb97ffa3eb2fb43166d22df1c?x-bce-process=image/resize,m_lfit,w_220,limit_1/format,f_auto',
              quantity: 1,
              stockStatus: false,
              stockQuantity: 0,
              price: '25900',
              originPrice: '39900',
              tagPrice: null,
              tagText: null,
              roomId: null,
              specInfo: [{
                  specTitle: '重量',
                  specValue: '5kg',
                },
                {
                  specTitle: '类型',
                  specValue: '大果',
                },
              ],
              joinCartTime: '2020-04-24T06:26:48.000+0000',
              available: 1,
              putOnSale: 1,
              etitle: null,
            }, ],
            lastJoinTime: null,
          },
        ],
        lastJoinTime: '2020-06-29T07:55:40.000+0000',
        postageFreePromotionVo: {
          title: null,
          promotionCode: null,
          promotionSubCode: null,
          promotionId: null,
          tagText: null,
          promotionStatus: null,
          tag: null,
          description: null,
          doorSillRemain: null,
          isNeedAddOnShop: 0,
        },
      }, ],
      invalidGoodItems: [{
        uid: '88888888205468',
        saasId: '88888888',
        storeId: '1000',
        spuId: '1',
        skuId: '135691631',
        isSelected: 1,
        thumb: 'https://cdn-we-retail.ym.tencent.com/tsr/goods/nz-08b.png',
        title: '纯色纯棉休闲圆领短袖T恤纯白亲肤厚柔软细腻面料纯白短袖套头T恤',
        primaryImage: 'https://cdn-we-retail.ym.tencent.com/tsr/goods/nz-08b.png',
        quantity: 8,
        stockStatus: true,
        stockQuantity: 177,
        price: '26900',
        originPrice: '31900',
        tagPrice: null,
        tagText: null,
        roomId: null,
        specInfo: [{
            specTitle: '颜色',
            specValue: '白色',
          },
          {
            specTitle: '尺码',
            specValue: 'S',
          },
        ],
        joinCartTime: '2020-04-28T04:03:59.000+0000',
        available: 1,
        putOnSale: 1,
        etitle: null,
      }, ],
      isAllSelected: false,
      selectedGoodsCount: 16,
      totalAmount: '179997',
      totalDiscountAmount: '110000',
    },
    code: 'Success',
    msg: null,
    requestId: mockReqId(),
    clientIp: mockIp(),
    rt: 269,
    success: true,
  };
  return resp;
}